// 8080 in the ORIGINAL STYLE ///

  // Move, load, store
  ( M: 'MOV';  A: 'B,B';    S: 02{mReg}; O: $40; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'B,C';    S: 02{mReg}; O: $41; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'B,D';    S: 02{mReg}; O: $42; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'B,E';    S: 02{mReg}; O: $43; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'B,H';    S: 02{mReg}; O: $44; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'B,L';    S: 02{mReg}; O: $45; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'B,M';    S: 02{mReg}; O: $46; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'B,A';    S: 02{mReg}; O: $47; N: 1; C:  5; R: rNIL; T: %01 ),

  ( M: 'MOV';  A: 'C,B';    S: 02{mReg}; O: $48; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'C,C';    S: 02{mReg}; O: $49; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'C,D';    S: 02{mReg}; O: $4A; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'C,E';    S: 02{mReg}; O: $4B; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'C,H';    S: 02{mReg}; O: $4C; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'C,L';    S: 02{mReg}; O: $4D; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'C,M';    S: 02{mReg}; O: $4E; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'C,A';    S: 02{mReg}; O: $4F; N: 1; C:  5; R: rNIL; T: %01 ),

  ( M: 'MOV';  A: 'D,B';    S: 02{mReg}; O: $50; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'D,C';    S: 02{mReg}; O: $51; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'D,D';    S: 02{mReg}; O: $52; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'D,E';    S: 02{mReg}; O: $53; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'D,H';    S: 02{mReg}; O: $54; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'D,L';    S: 02{mReg}; O: $55; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'D,M';    S: 02{mReg}; O: $56; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'D,A';    S: 02{mReg}; O: $57; N: 1; C:  5; R: rNIL; T: %01 ),

  ( M: 'MOV';  A: 'E,B';    S: 02{mReg}; O: $58; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'E,C';    S: 02{mReg}; O: $59; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'E,D';    S: 02{mReg}; O: $5A; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'E,E';    S: 02{mReg}; O: $5B; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'E,H';    S: 02{mReg}; O: $5C; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'E,L';    S: 02{mReg}; O: $5D; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'E,M';    S: 02{mReg}; O: $5E; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'E,A';    S: 02{mReg}; O: $5F; N: 1; C:  5; R: rNIL; T: %01 ),

  ( M: 'MOV';  A: 'H,B';   S: 02{mReg}; O: $60; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'H,C';   S: 02{mReg}; O: $61; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'H,D';   S: 02{mReg}; O: $62; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'H,E';   S: 02{mReg}; O: $63; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'H,H';   S: 02{mReg}; O: $64; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'H,L';   S: 02{mReg}; O: $65; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'H,M';   S: 02{mReg}; O: $66; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'H,A';   S: 02{mReg}; O: $67; N: 1; C:  5; R: rNIL; T: %01 ),

  ( M: 'MOV';  A: 'L,B';   S: 02{mReg}; O: $68; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'L,C';   S: 02{mReg}; O: $69; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'L,D';   S: 02{mReg}; O: $6A; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'L,E';   S: 02{mReg}; O: $6B; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'L,H';   S: 02{mReg}; O: $6C; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'L,L';   S: 02{mReg}; O: $6D; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'L,M';   S: 02{mReg}; O: $6E; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'L,A';   S: 02{mReg}; O: $6F; N: 1; C:  5; R: rNIL; T: %01 ),

  ( M: 'MOV';  A: 'M,B';   S: 02{mReg}; O: $70; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'M,C';   S: 02{mReg}; O: $71; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'M,D';   S: 02{mReg}; O: $72; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'M,E';   S: 02{mReg}; O: $73; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'M,H';   S: 02{mReg}; O: $74; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'M,L';   S: 02{mReg}; O: $75; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'M,A';   S: 02{mReg}; O: $77; N: 1; C:  7; R: rNIL; T: %01 ),

  ( M: 'MOV';  A: 'A,B';   S: 02{mReg}; O: $78; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'A,C';   S: 02{mReg}; O: $79; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'A,D';   S: 02{mReg}; O: $7A; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'A,E';   S: 02{mReg}; O: $7B; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'A,H';   S: 02{mReg}; O: $7C; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'A,L';   S: 02{mReg}; O: $7D; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'A,M';   S: 02{mReg}; O: $7E; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'MOV';  A: 'A,A';   S: 02{mReg}; O: $7F; N: 1; C:  5; R: rNIL; T: %01 ),

  ( M: 'MVI';  A: 'B,*';   S: 03{mIMM}; O: $06; N: 2; C:  7; R: rNIL; T: %01 ),
  ( M: 'MVI';  A: 'C,*';   S: 03{mIMM}; O: $0E; N: 2; C:  7; R: rNIL; T: %01 ),
  ( M: 'MVI';  A: 'D,*';   S: 03{mIMM}; O: $16; N: 2; C:  7; R: rNIL; T: %01 ),
  ( M: 'MVI';  A: 'E,*';   S: 03{mIMM}; O: $1E; N: 2; C:  7; R: rNIL; T: %01 ),
  ( M: 'MVI';  A: 'H,*';   S: 03{mIMM}; O: $26; N: 2; C:  7; R: rNIL; T: %01 ),
  ( M: 'MVI';  A: 'L,*';   S: 03{mIMM}; O: $2E; N: 2; C:  7; R: rNIL; T: %01 ),
  ( M: 'MVI';  A: 'M,*';   S: 03{mIMM}; O: $36; N: 2; C:  7; R: rNIL; T: %01 ),
  ( M: 'MVI';  A: 'A,*';   S: 03{mIMM}; O: $3E; N: 2; C:  7; R: rNIL; T: %01 ),

  ( M: 'LDAX'; A: 'B';     S: 02{mReg}; O: $0A; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'LDAX'; A: 'D';     S: 02{mReg}; O: $1A; N: 1; C:  7; R: rNIL; T: %01 ),

  ( M: 'STAX'; A: 'B';     S: 02{mReg}; O: $02; N: 1; C:  7; R: rNIL; T: %01 ),
  ( M: 'STAX'; A: 'D';     S: 02{mReg}; O: $12; N: 1; C:  7; R: rNIL; T: %01 ),

  ( M: 'LXI';  A: 'B,*';   S: 04{mIMM}; O: $01; N: 3; C: 10; R: rNIL; T: %01 ),
  ( M: 'LXI';  A: 'D,*';   S: 04{mIMM}; O: $11; N: 3; C: 10; R: rNIL; T: %01 ),
  ( M: 'LXI';  A: 'H,*';   S: 04{mIMM}; O: $21; N: 3; C: 10; R: rNIL; T: %01 ),
  ( M: 'LXI';  A: 'SP,*';  S: 04{mIMM}; O: $31; N: 3; C: 10; R: rNIL; T: %01 ),

  ( M: 'SHLD'; A: '*';     S: 04{mDir}; O: $22; N: 3; C: 16; R: rNIL; T: %01 ),
  ( M: 'LHLD'; A: '*';     S: 04{mDir}; O: $2A; N: 3; C: 16; R: rNIL; T: %01 ),
  ( M: 'STA';  A: '*';     S: 04{mDir}; O: $32; N: 3; C: 13; R: rNIL; T: %01 ),
  ( M: 'LDA';  A: '*';     S: 04{mDir}; O: $3A; N: 3; C: 13; R: rNIL; T: %01 ),

  ( M: 'SPHL'; A: '';      S: 02{mReg}; O: $F9; N: 1; C:  5; R: rNIL; T: %01 ),

  ( M: 'XCHG'; A: '';      S: 02{mReg}; O: $EB; N: 1; C:  4; R: rNIL; T: %01 ),
  ( M: 'XTHL'; A: '';      S: 02{mReg}; O: $E3; N: 1; C: 18; R: rNIL; T: %01 ),

  // Stack Ops
  ( M: 'PUSH'; A: 'B';     S: 02{mReg}; O: $C5; N: 1; C: 11; R: rNIL; T: %01 ),
  ( M: 'PUSH'; A: 'D';     S: 02{mReg}; O: $D5; N: 1; C: 11; R: rNIL; T: %01 ),
  ( M: 'PUSH'; A: 'H';     S: 02{mReg}; O: $E5; N: 1; C: 11; R: rNIL; T: %01 ),
  ( M: 'PUSH'; A: 'PSW';   S: 02{mReg}; O: $F5; N: 1; C: 11; R: rNIL; T: %01 ),

  ( M: 'POP';  A: 'B';     S: 02{mReg}; O: $C1; N: 1; C: 10; R: rNIL; T: %01 ),
  ( M: 'POP';  A: 'D';     S: 02{mReg}; O: $D1; N: 1; C: 10; R: rNIL; T: %01 ),
  ( M: 'POP';  A: 'H';     S: 02{mReg}; O: $E1; N: 1; C: 10; R: rNIL; T: %01 ),
  ( M: 'POP';  A: 'PSW';   S: 02{mReg}; O: $F1; N: 1; C: 10; R: rNIL; T: %01 ),

  // Jump
  ( M: 'JNZ';  A: '*';     S: 04{mDir}; O: $C2; N: 3; C: 10; R: rNIL; T: %01 ),
  ( M: 'JZ';   A: '*';     S: 04{mDir}; O: $CA; N: 3; C: 10; R: rNIL; T: %01 ),
  ( M: 'JNC';  A: '*';     S: 04{mDir}; O: $D2; N: 3; C: 10; R: rNIL; T: %01 ),
  ( M: 'JC';   A: '*';     S: 04{mDir}; O: $DA; N: 3; C: 10; R: rNIL; T: %01 ),
  ( M: 'JPO';  A: '*';     S: 04{mDir}; O: $E2; N: 3; C: 10; R: rNIL; T: %01 ),
  ( M: 'JPE';  A: '*';     S: 04{mDir}; O: $EA; N: 3; C: 10; R: rNIL; T: %01 ),
  ( M: 'JP';   A: '*';     S: 04{mDir}; O: $F2; N: 3; C: 10; R: rNIL; T: %01 ),
  ( M: 'JM';   A: '*';     S: 04{mDir}; O: $FA; N: 3; C: 10; R: rNIL; T: %01 ),
  ( M: 'PCHL'; A: '';      S: 02{mReg}; O: $E9; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'JMP';  A: '*';     S: 04{mDir}; O: $C3; N: 3; C: 10; R: rNIL; T: %01 ),

  // Call
  ( M: 'CNZ';  A: '*';     S: 04{mDir}; O: $C4; N: 3; C: 11; R: rNIL; T: %01 ),
  ( M: 'CZ';   A: '*';     S: 04{mDir}; O: $CC; N: 3; C: 11; R: rNIL; T: %01 ),
  ( M: 'CNC';  A: '*';     S: 04{mDir}; O: $D4; N: 3; C: 11; R: rNIL; T: %01 ),
  ( M: 'CC';   A: '*';     S: 04{mDir}; O: $DC; N: 3; C: 11; R: rNIL; T: %01 ),
  ( M: 'CPO';  A: '*';     S: 04{mDir}; O: $E4; N: 3; C: 11; R: rNIL; T: %01 ),
  ( M: 'CPE';  A: '*';     S: 04{mDir}; O: $EC; N: 3; C: 11; R: rNIL; T: %01 ),
  ( M: 'CP';   A: '*';     S: 04{mDir}; O: $F4; N: 3; C: 11; R: rNIL; T: %01 ),
  ( M: 'CM';   A: '*';     S: 04{mDir}; O: $FC; N: 3; C: 11; R: rNIL; T: %01 ),
  ( M: 'CALL'; A: '*';     S: 04{mDir}; O: $CD; N: 3; C: 17; R: rNIL; T: %01 ),

  // Return
  ( M: 'RNZ';  A: '';      S: 01{mINH}; O: $C0; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'RZ';   A: '';      S: 01{mINH}; O: $C8; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'RNC';  A: '';      S: 01{mINH}; O: $D0; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'RC';   A: '';      S: 01{mINH}; O: $D8; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'RPO';  A: '';      S: 01{mINH}; O: $E0; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'RPE';  A: '';      S: 01{mINH}; O: $E8; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'RP';   A: '';      S: 01{mINH}; O: $F0; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'RM';   A: '';      S: 01{mINH}; O: $F8; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'RET';  A: '';      S: 01{mINH}; O: $C9; N: 1; C: 10; R: rNIL; T: %01 ),

  // Restart
  ( M: 'RST';  A: '0';     S: 01{mINH}; O: $C7; N: 1; C: 11; R: rNIL; T: %01 ),
  ( M: 'RST';  A: '1';     S: 01{mINH}; O: $CF; N: 1; C: 11; R: rNIL; T: %01 ),
  ( M: 'RST';  A: '2';     S: 01{mINH}; O: $D7; N: 1; C: 11; R: rNIL; T: %01 ),
  ( M: 'RST';  A: '3';     S: 01{mINH}; O: $DF; N: 1; C: 11; R: rNIL; T: %01 ),
  ( M: 'RST';  A: '4';     S: 01{mINH}; O: $E7; N: 1; C: 11; R: rNIL; T: %01 ),
  ( M: 'RST';  A: '5';     S: 01{mINH}; O: $EF; N: 1; C: 11; R: rNIL; T: %01 ),
  ( M: 'RST';  A: '6';     S: 01{mINH}; O: $F7; N: 1; C: 11; R: rNIL; T: %01 ),
  ( M: 'RST';  A: '7';     S: 01{mINH}; O: $FF; N: 1; C: 11; R: rNIL; T: %01 ),

  // Increment and Decrement
  ( M: 'INR';  A: 'B';     S: 02{mReg}; O: $04; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'INR';  A: 'C';     S: 02{mReg}; O: $0C; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'INR';  A: 'D';     S: 02{mReg}; O: $14; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'INR';  A: 'E';     S: 02{mReg}; O: $1C; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'INR';  A: 'H';     S: 02{mReg}; O: $24; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'INR';  A: 'L';     S: 02{mReg}; O: $2C; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'INR';  A: 'A';     S: 02{mReg}; O: $3C; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'INR';  A: 'M';     S: 02{mReg}; O: $34; N: 1; C: 10; R: rNIL; T: %01 ),

  ( M: 'INX';  A: 'B';     S: 02{mReg}; O: $03; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'INX';  A: 'D';     S: 02{mReg}; O: $13; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'INX';  A: 'H';     S: 02{mReg}; O: $23; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'INX';  A: 'SP';    S: 02{mReg}; O: $33; N: 1; C:  5; R: rNIL; T: %01 ),

  ( M: 'DCR';  A: 'B';     S: 02{mReg}; O: $05; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'DCR';  A: 'C';     S: 02{mReg}; O: $0D; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'DCR';  A: 'D';     S: 02{mReg}; O: $15; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'DCR';  A: 'E';     S: 02{mReg}; O: $1D; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'DCR';  A: 'H';     S: 02{mReg}; O: $25; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'DCR';  A: 'L';     S: 02{mReg}; O: $2D; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'DCR';  A: 'A';     S: 02{mReg}; O: $3D; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'DCR';  A: 'M';     S: 02{mReg}; O: $35; N: 1; C: 10; R: rNIL; T: %01 ),

  ( M: 'DCX';  A: 'B';     S: 02{mReg}; O: $0B; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'DCX';  A: 'D';     S: 02{mReg}; O: $1B; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'DCX';  A: 'H';     S: 02{mReg}; O: $2B; N: 1; C:  5; R: rNIL; T: %01 ),
  ( M: 'DCX';  A: 'SP';    S: 02{mReg}; O: $3B; N: 1; C:  5; R: rNIL; T: %01 ),

  // Add
  ( M: 'ADD';  A: 'B';     S: 02{mReg}; O: $80; N: 1; C: 4;  R: rNIL; T: %01 ), //Y...
  ( M: 'ADD';  A: 'C';     S: 02{mReg}; O: $81; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ADD';  A: 'D';     S: 02{mReg}; O: $82; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ADD';  A: 'E';     S: 02{mReg}; O: $83; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ADD';  A: 'H';     S: 02{mReg}; O: $84; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ADD';  A: 'L';     S: 02{mReg}; O: $85; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ADD';  A: 'M';     S: 02{mReg}; O: $86; N: 1; C: 7;  R: rNIL; T: %01 ),
  ( M: 'ADD';  A: 'A';     S: 02{mReg}; O: $87; N: 1; C: 4;  R: rNIL; T: %01 ),

  ( M: 'ADI';  A: '*';     S: 03{mIMM}; O: $C6; N: 2; C: 7;  R: rNIL; T: %01 ),

  ( M: 'DAD';  A: 'B';     S: 02{mReg}; O: $09; N: 1; C: 10; R: rNIL; T: %01 ),
  ( M: 'DAD';  A: 'D';     S: 02{mReg}; O: $19; N: 1; C: 10; R: rNIL; T: %01 ),
  ( M: 'DAD';  A: 'H';     S: 02{mReg}; O: $29; N: 1; C: 10; R: rNIL; T: %01 ),
  ( M: 'DAD';  A: 'SP';    S: 02{mReg}; O: $39; N: 1; C: 10; R: rNIL; T: %01 ),

  ( M: 'ADC';  A: 'B';     S: 02{mReg}; O: $88; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ADC';  A: 'C';     S: 02{mReg}; O: $89; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ADC';  A: 'D';     S: 02{mReg}; O: $8A; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ADC';  A: 'E';     S: 02{mReg}; O: $8B; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ADC';  A: 'H';     S: 02{mReg}; O: $8C; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ADC';  A: 'L';     S: 02{mReg}; O: $8D; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ADC';  A: 'M';     S: 02{mReg}; O: $8E; N: 1; C: 7;  R: rNIL; T: %01 ),
  ( M: 'ADC';  A: 'A';     S: 02{mReg}; O: $8F; N: 1; C: 4;  R: rNIL; T: %01 ),

  ( M: 'ACI';  A: '*';     S: 03{mIMM}; O: $CE; N: 2; C: 7;  R: rNIL; T: %01 ),

  // Sub
  ( M: 'SUB';  A: 'B';     S: 02{mReg}; O: $90; N: 1; C: 4;  R: rNIL; T: %01 ), //Y...
  ( M: 'SUB';  A: 'C';     S: 02{mReg}; O: $91; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'SUB';  A: 'D';     S: 02{mReg}; O: $92; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'SUB';  A: 'E';     S: 02{mReg}; O: $93; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'SUB';  A: 'H';     S: 02{mReg}; O: $94; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'SUB';  A: 'L';     S: 02{mReg}; O: $95; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'SUB';  A: 'M';     S: 02{mReg}; O: $96; N: 1; C: 7;  R: rNIL; T: %01 ),
  ( M: 'SUB';  A: 'A';     S: 02{mReg}; O: $97; N: 1; C: 4;  R: rNIL; T: %01 ),

  ( M: 'SUI';  A: '*';     S: 03{mIMM}; O: $D6; N: 2; C: 7;  R: rNIL; T: %01 ),

  ( M: 'SBB';  A: 'B';     S: 02{mReg}; O: $98; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'SBB';  A: 'C';     S: 02{mReg}; O: $99; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'SBB';  A: 'D';     S: 02{mReg}; O: $9A; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'SBB';  A: 'E';     S: 02{mReg}; O: $9B; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'SBB';  A: 'H';     S: 02{mReg}; O: $9C; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'SBB';  A: 'L';     S: 02{mReg}; O: $9D; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'SBB';  A: 'M';     S: 02{mReg}; O: $9E; N: 1; C: 7;  R: rNIL; T: %01 ),
  ( M: 'SBB';  A: 'A';     S: 02{mReg}; O: $9F; N: 1; C: 4;  R: rNIL; T: %01 ),

  ( M: 'SBI';  A: '*';     S: 03{mIMM}; O: $DE; N: 2; C: 7;  R: rNIL; T: %01 ),

  // Logical
  ( M: 'ANA';  A: 'B';     S: 02{mReg}; O: $A0; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ANA';  A: 'C';     S: 02{mReg}; O: $A1; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ANA';  A: 'D';     S: 02{mReg}; O: $A2; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ANA';  A: 'E';     S: 02{mReg}; O: $A3; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ANA';  A: 'H';     S: 02{mReg}; O: $A4; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ANA';  A: 'L';     S: 02{mReg}; O: $A5; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ANA';  A: 'M';     S: 02{mReg}; O: $A6; N: 1; C: 7;  R: rNIL; T: %01 ),
  ( M: 'ANA';  A: 'A';     S: 02{mReg}; O: $A7; N: 1; C: 4;  R: rNIL; T: %01 ),

  ( M: 'ANI';  A: '*';     S: 03{mIMM}; O: $E6; N: 2; C: 7;  R: rNIL; T: %01 ),

  ( M: 'XRA';  A: 'B';     S: 02{mReg}; O: $A8; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'XRA';  A: 'C';     S: 02{mReg}; O: $A9; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'XRA';  A: 'D';     S: 02{mReg}; O: $AA; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'XRA';  A: 'E';     S: 02{mReg}; O: $AB; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'XRA';  A: 'H';     S: 02{mReg}; O: $AC; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'XRA';  A: 'L';     S: 02{mReg}; O: $AD; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'XRA';  A: 'M';     S: 02{mReg}; O: $AE; N: 1; C: 7;  R: rNIL; T: %01 ),
  ( M: 'XRA';  A: 'A';     S: 02{mReg}; O: $AF; N: 1; C: 4;  R: rNIL; T: %01 ),

  ( M: 'XRI';  A: '*';     S: 03{mIMM}; O: $EE; N: 2; C: 7;  R: rNIL; T: %01 ),

  ( M: 'ORA';  A: 'B';     S: 02{mReg}; O: $B0; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ORA';  A: 'C';     S: 02{mReg}; O: $B1; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ORA';  A: 'D';     S: 02{mReg}; O: $B2; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ORA';  A: 'E';     S: 02{mReg}; O: $B3; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ORA';  A: 'H';     S: 02{mReg}; O: $B4; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ORA';  A: 'L';     S: 02{mReg}; O: $B5; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'ORA';  A: 'M';     S: 02{mReg}; O: $B6; N: 1; C: 7;  R: rNIL; T: %01 ),
  ( M: 'ORA';  A: 'A';     S: 02{mReg}; O: $B7; N: 1; C: 4;  R: rNIL; T: %01 ),

  ( M: 'ORI';  A: '*';     S: 03{mIMM}; O: $F6; N: 2; C: 7;  R: rNIL; T: %01 ),

  ( M: 'CMP';  A: 'B';     S: 02{mReg}; O: $B8; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'CMP';  A: 'C';     S: 02{mReg}; O: $B9; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'CMP';  A: 'D';     S: 02{mReg}; O: $BA; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'CMP';  A: 'E';     S: 02{mReg}; O: $BB; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'CMP';  A: 'H';     S: 02{mReg}; O: $BC; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'CMP';  A: 'L';     S: 02{mReg}; O: $BD; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'CMP';  A: 'M';     S: 02{mReg}; O: $BE; N: 1; C: 7;  R: rNIL; T: %01 ),
  ( M: 'CMP';  A: 'A';     S: 02{mReg}; O: $BF; N: 1; C: 4;  R: rNIL; T: %01 ),

  ( M: 'CPI';  A: '*';     S: 03{mIMM}; O: $FE; N: 2; C: 7;  R: rNIL; T: %01 ),

  // Rotate
  ( M: 'RLC';  A: '';      S: 01{mINH}; O: $07; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'RRC';  A: '';      S: 01{mINH}; O: $0F; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'RAL';  A: '';      S: 01{mINH}; O: $17; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'RAR';  A: '';      S: 01{mINH}; O: $1F; N: 1; C: 4;  R: rNIL; T: %01 ),

  // Specials
  ( M: 'CMA';  A: '';      S: 01{mINH}; O: $2F; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'STC';  A: '';      S: 01{mINH}; O: $37; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'CMC';  A: '';      S: 01{mINH}; O: $3F; N: 1; C: 4;  R: rNIL; T: %01 ),
  ( M: 'DAA';  A: '';      S: 01{mINH}; O: $27; N: 1; C: 4;  R: rNIL; T: %01 ),

  // Input / Output
  ( M: 'OUT';  A: '*';     S: 03{mIMM}; O: $D3; N: 2; C: 10; R: rNIL; T: %01 ),
  ( M: 'IN';   A: '*';     S: 03{mIMM}; O: $DB; N: 2; C: 10; R: rNIL; T: %01 ),

  // Control
  ( M: 'EI';   A: '';      S: 01{mINH}; O: $FB; N: 1; C:  4; R: rNIL; T: %01 ),
  ( M: 'DI';   A: '';      S: 01{mINH}; O: $F3; N: 1; C:  4; R: rNIL; T: %01 ),
  ( M: 'NOP';  A: '';      S: 01{mINH}; O: $00; N: 1; C:  4; R: rNIL; T: %01 ),
  ( M: 'HLT';  A: '';      S: 01{mINH}; O: $76; N: 1; C: 7;  R: rNIL; T: %01 ),

